# Generated by Django 6.1.1 on 2026-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_agendamentos'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendamentos',
            constraint=models.UniqueConstraint(fields=('veterinario', 'data', 'horario'), name='agendamento_unico_por_veterinario'),
        ),
    ]
