# Generated by Django 6.1.1 on 2026-09-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_agendamentos_agendamento_unico_por_veterinario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamentos',
            options={'verbose_name_plural': 'Agendamentos'},
        ),
    ]
